### ISSUE TITLE
I Got You A Free Domain!

### ISSUE THREAD

**Issue by ConvexPolygon** [geographix/geographix.github.io#9]
Hey Geo!
I just got you [this](http://geographix.cf) website and pointed it to your github pages website. Now all you need to do to activate it is go to the github pages settings and switch it to custom domain with force https off. Point it to geographix.cf

**Comment by geographix** [comment]
Okay, thanks!

**Comment by geographix** [comment]
Wait, why are we using the Central African Rep. official national domain?

**Comment by ConvexPolygon** [comment]
Because it's free.

**Comment by geographix** [comment]
xD
